### ISSUE TITLE
TypeError: Current driver does not support http client

### ISSUE THREAD

**Issue by Suica0w0** [noneplugin/nonebot-plugin-imagetools#14]
01-03 02:03:24 [WARNING] nonebot_plugin_imagetools | Fail to fetch image: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NoneBot\Scripts\SuicaBot\.venv\lib\site-packages\nonebot_plugin_imagetools\depends.py", line 34, in dependency
    result = await image_fetch(
  File "C:\Users\Administrator\Desktop\NoneBot\Scripts\SuicaBot\.venv\lib\site-packages\nonebot_plugin_alconna\uniseg\tools.py", line 32, in image_fetch
    resp = await bot.adapter.request(req)
  File "C:\Users\Administrator\Desktop\NoneBot\Scripts\SuicaBot\.venv\lib\site-packages\nonebot\internal\adapter\adapter.py", line 89, in request
    raise TypeError("Current driver does not support http client")
TypeError: Current driver does not support http client

**Comment by MeetWq** [comment]
https://github.com/noneplugin/nonebot-plugin-memes/issues/69
